---
title: "Event Reference Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Event Reference Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Event Reference Example

The following example just prints information to the console about the 
events that are happening in the window.



```{r setup, eval = FALSE}
library(eventloop)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' This is a verbose callback that simply prints information to the console
#' about what events are happening
#' 
#' Press ESC to quit.
#' 
#' @param event The event from the graphics device. Is NULL when no event
#'        occurred.  Otherwise has `type` element set to:
#'        `event$type = 'mouse_down'` 
#'               - an event in which a mouse button was pressed
#'               - `event$button` gives the index of the button
#'        `event$type = 'mouse_up'`   
#'               - a mouse button was released
#'        `event$type = 'key_press'`  
#'               - a key was pressed
#'               - `event$char` holds the character as string
#'               - `event$int` holds the integer representation
#' @param mouse_x,mouse_y current location of mouse within window. If mouse is 
#'        not within window, this will be set to the last available coordinates
#' @param frame_num integer count of which frame this is
#' @param fps_actual,fps_target the curent framerate and the framerate specified
#'        by the user
#' @param dev_width,dev_height the width and height of the output device. Note:
#'        this does not cope well if you resize the window
#' @param ... any extra arguments ignored
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
verbose <- function(event, mouse_x, mouse_y, frame_num, fps_actual,
                    fps_target, dev_width, dev_height, ...) {
  
  if (!is.null(event)) {
    co <- sprintf("[%.2f, %.2f]", mouse_x, mouse_y)
    if (event$type %in% c('mouse_down', 'mouse_up')) {
      cat(co, "Mouse: ", event$type, " - button: ", event$button, "\n")
    } else if (event$type == 'mouse_move') {
      cat(co, "Move \n")
    } else if (event$type == 'key_press') {
      cat(co, "Key: ", event$char, " - integer value [", event$int, "]\n")
    }
  }
}



eventloop::run_loop(verbose, fps_target = 10, show_fps = TRUE)
```
