---
title: "Realtime Plot Updates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Realtime Plot Updates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(grid)
library(eventloop)
```




```{r eval = FALSE}
 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Initialise a number of data streams
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
N        <- 20
Nstreams <- 100
streams  <- lapply(seq(Nstreams), function(x) rep(0.5, N))
alpha    <- 0.05
cols     <- rainbow(Nstreams)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The plotting/behaviour at each call doesn't actually depend on anything
# the user is doing, so just ignore all arguments
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
monitor_status <- function(...) {
  
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Update all streams by pulling a new value from the source.
  # In this simple example, the datasource is just 'runif(1)'
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  streams <<- lapply(
    streams,
    function(stream) {
      c(
        stream[2:N],
        alpha * runif(1) + (1 - alpha) * stream[N]
      )
    }
  )

  
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Clear the screen
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  grid.rect(gp = gpar(fill = 'white'))
  
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Plot the data streams in different colours
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  for (i in seq_along(streams)) {
    grid.lines(
      x = seq.int(0, 1, length.out = N),
      y = streams[[i]],
      gp = gpar(col = cols[[i]])
    )
  }
  
  
}

run_loop(monitor_status, show_fps = TRUE, fps_target = 30)
```

 <video controls>
  <source src="images/plotting.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video> 


