---
title: "Reactive Objects 2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reactive Objects 2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
library(eventloop)
library(grid)
library(viridisLite)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Data.frame of point (x,y) r, fill information
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
library(grid)

N <- 33
r <- 1/N/2
decay    <- 0.004
min_size <- 0.1
points <- expand.grid(
  x = seq(N)/N - r,
  y = seq(N)/N - r,
  r = r,
  scale = min_size
)

# points$fill <- sample(viridisLite::cividis(20), nrow(points), replace = TRUE)
points$fill <- viridisLite::magma(nrow(points))

scale <- rep(min_size, nrow(points))


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Activate points within the board when the mouse is near
#' 
#' Press ESC to quit.
#'
#' @param event The event from the graphics device. Is NULL when no event
#'        occurred.  Otherwise has `type` element set to:
#'        `event$type = 'mouse_down'` 
#'               - an event in which a mouse button was pressed
#'               - `event$button` gives the index of the button
#'        `event$type = 'mouse_up'`   
#'               - a mouse button was released
#'        `event$type = 'key_press'`  
#'               - a key was pressed
#'               - `event$char` holds the character as string
#'               - `event$int` holds the integer representation
#' @param mouse_x,mouse_y current location of mouse within window. If mouse is 
#'        not within window, this will be set to the last available coordinates
#' @param frame_num integer count of which frame this is
#' @param fps_actual,fps_target the curent framerate and the framerate specified
#'        by the user
#' @param dev_width,dev_height the width and height of the output device. Note:
#'        this does not cope well if you resize the window
#' @param ... any extra arguments ignored
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
canvas <- function(event, mouse_x, mouse_y, ...) {

  # Highlight points near mouse
  near <- (abs(points$x - mouse_x)+ abs(points$y - mouse_y)) < (1.4 * r)
  scale[near] <<- 1

  # Draw all the points
  grid::grid.rect(gp = grid::gpar(fill = 'white'))
  grid::grid.rect(
    x = points$x,
    y = points$y,
    width  = 2 * points$r * scale,
    height = 2 * points$r * scale,
    gp = grid::gpar(fill = points$fill, col = NA)
  )

  # decay the size of each point
  scale <<- pmax(scale - decay, min_size)
}


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Run the loop
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_loop(canvas, 10, 10, fps_target = 30)
```


<video controls>
  <source src="images/interact.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video> 
