---
title: "Starfield"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Starfield}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval = FALSE}
library(eventloop)
library(grid)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Global variables for starfield:
#   The x,y positions of each point in 'npc' coordinates - in range [0, 1]
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xs <- runif(1000)
ys <- runif(1000)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Draw a rotating/expanding starfield where the spawn point follows the mouse
#' 
#' Press ESC to quit.
#'
#' @param event The event from the graphics device. Is NULL when no event
#'        occurred.  Otherwise has `type` element set to:
#'        `event$type = 'mouse_down'` 
#'               - an event in which a mouse button was pressed
#'               - `event$button` gives the index of the button
#'        `event$type = 'mouse_up'`   
#'               - a mouse button was released
#'        `event$type = 'key_press'`  
#'               - a key was pressed
#'               - `event$char` holds the character as string
#'               - `event$int` holds the integer representation
#' @param mouse_x,mouse_y current location of mouse within window. If mouse is 
#'        not within window, this will be set to the last available coordinates
#' @param frame_num integer count of which frame this is
#' @param fps_actual,fps_target the curent framerate and the framerate specified
#'        by the user
#' @param dev_width,dev_height the width and height of the output device. Note:
#'        this does not cope well if you resize the window
#' @param ... any extra arguments ignored
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
starfield <- function(event, mouse_x, mouse_y, frame_num, fps_actual,
                         fps_target, dev_width, dev_height, ...) {

  # Set the centre for expansion/rotation to be the current mouse (x,y)
  # could just set to centre to (0.5, 0.5) for non-interactive case
  xcentre <- mouse_x
  ycentre <- mouse_y

  # Expand points around centre
  xt <- (xs - xcentre) * 1.03
  yt <- (ys - ycentre) * 1.03

  # Rotate points around centre
  theta <- 1.5 * pi/180
  xs <<- xt * cos(theta) - yt * sin(theta) + xcentre
  ys <<- xt * sin(theta) + yt * cos(theta) + ycentre

  # Replace any out-of-bound points with new random points
  out_of_bounds <- which(xs < 0 | xs > 1 | ys < 0 | ys > 1)
  N <- length(out_of_bounds)
  if (N > 0) {
    xs[out_of_bounds] <<- runif(N, xcentre - 0.05, xcentre + 0.05)
    ys[out_of_bounds] <<- runif(N, ycentre - 0.05, ycentre + 0.05)
  }

  # Clear screen, plot points, add in FPS info in bottom corner
  grid::grid.rect(gp = grid::gpar(fill = 'white'))
  grid::grid.points(
    x = grid::unit(xs, 'npc'),
    y = grid::unit(ys, 'npc'),
    pch = '+'
  )
}


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Start an interactive render loop around this function
# Note: Your OS must support this device:  x11(type = 'dbcairo')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_loop(starfield, fps_target = NA)
```



<video controls>
  <source src="images/starfield.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video> 
