---
title: "Physics Simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Physics Simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(grid)
library(eventloop)

# remotes::install_github("coolbutuseless/chipmunkcore")
# remotes::install_github("coolbutuseless/chipmunkbasic")
library(chipmunkcore)
library(chipmunkbasic)
```


```{r eval = FALSE}
set.seed(1)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Initialize a simulation space
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cm <- Chipmunk$new()

scale <- 100

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Add fixed segments
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cm$add_static_segment(0.1 * scale, 0.5 * scale ,   0.6 * scale, 0.3  * scale, friction = 0.2, elasticity = 1)
cm$add_static_segment(0.9 * scale, 0.35 * scale,   0.4 * scale, 0.05 * scale, friction = 0.2, elasticity = 1)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Fetch all the segments. Use for plotting
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
segments_df <- cm$get_static_segments()

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Add some circles 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
for (i in 1:10) {
  cm$add_circle(
    x  = runif(1) * scale,
    y  = runif(1) * scale,
    vx = 5 * rnorm(1),
    vy = 5 * rnorm(1)
  )
}


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Simulate physics of the balls i nthe sphere. Add new balls when mouse 
#' is clicked
#' 
#' Press ESC to quit.
#'
#' @param event The event from the graphics device. Is NULL when no event
#'        occurred.  Otherwise has `type` element set to:
#'        `event$type = 'mouse_down'` 
#'               - an event in which a mouse button was pressed
#'               - `event$button` gives the index of the button
#'        `event$type = 'mouse_up'`   
#'               - a mouse button was released
#'        `event$type = 'key_press'`  
#'               - a key was pressed
#'               - `event$char` holds the character as string
#'               - `event$int` holds the integer representation
#' @param mouse_x,mouse_y current location of mouse within window. If mouse is 
#'        not within window, this will be set to the last available coordinates
#' @param frame_num integer count of which frame this is
#' @param fps_actual,fps_target the curent framerate and the framerate specified
#'        by the user
#' @param dev_width,dev_height the width and height of the output device. Note:
#'        this does not cope well if you resize the window
#' @param ... any extra arguments ignored
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sim <- function(event, mouse_x, mouse_y, ...) {
  circles <- cm$get_circles()
  cm$advance(1)
  
  if (!is.null(event)) {
    if (event$type == 'mouse_down') {
      cm$add_circle(x = mouse_x * 100, y = mouse_y * 100)
    }
  }
  
  grid::grid.rect(gp = gpar(fill = 'white'))
  
  grid::grid.lines(
    x = c(0.1, 0.6),
    y = c(0.5, 0.3)
  )
  
  grid::grid.lines(
    x = c(0.9, 0.4),
    y = c(0.35, 0.05)
  )
  
  grid::grid.circle(
    x = circles$x / scale,
    y = circles$y / scale,
    r = unit(2, 'mm'),
    gp = gpar(fill = rainbow(nrow(circles)), col = NA)
  )
}

do_nothing <- function(...) {NULL}
eventloop::run_loop(sim, width = 7, height = 7, show_fps = TRUE, fps_target = 30)
```



 <video controls>
  <source src="images/physics.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video> 

