---
title: "Event Reference Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Event Reference Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Event Reference Example

The following example callback function, when run within the event loop, 
prints information to the console about the events that are happening in the window.

This could be a good place to start if developing code from scratch.


```{r eval = FALSE}
library(eventloop)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Global variables to keep some state information between calls
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
last_x <- NA
last_y <- NA


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' This is a verbose callback that simply prints information to the console
#' about what events are happening
#' 
#' Press ESC to quit.
#' 
#' @param event The event from the graphics device. Is NULL when no event
#'        occurred.  Otherwise has `type` element set to:
#'        `event$type = 'mouse_down'` 
#'               - an event in which a mouse button was pressed
#'               - `event$button` gives the index of the button
#'        `event$type = 'mouse_up'`   
#'               - a mouse button was released
#'        `event$type = 'mouse_move'`   
#'               - mouse was moved 
#'        `event$type = 'key_press'`  
#'               - a key was pressed
#'               - `event$char` holds the character as string
#'               - `event$int` holds the integer representation
#' @param mouse_x,mouse_y current location of mouse within window. If mouse is 
#'        not within window, this will be set to the last available coordinates
#' @param frame_num integer count of which frame this is
#' @param fps_actual,fps_target the curent framerate and the framerate specified
#'        by the user
#' @param dev_width,dev_height the width and height of the output device. Note:
#'        this does not cope well if you resize the window
#' @param ... any extra arguments ignored
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
verbose <- function(event, mouse_x, mouse_y, frame_num, fps_actual,
                    fps_target, dev_width, dev_height, ...) {
  
  # Did an event happen at all in this window?
  if (!is.null(event)) {
    
    # Draw a line
    if (!is.na(last_x)) {
      grid::grid.lines(
        x = c(last_x, mouse_x),
        y = c(last_y, mouse_y)
      )
    }
    
    # Keep track of latest mouse position
    last_x <<- mouse_x
    last_y <<- mouse_y
    
    # "Handle" the event by printing to console
    co <- sprintf("[%.2f, %.2f]", mouse_x, mouse_y)
    if (event$type %in% c('mouse_down', 'mouse_up', 'mouse_move')) {
      cat(co, "Mouse: ", event$type, " - button: ", event$button, "\n")
    } else if (event$type == 'mouse_move') {
      cat(co, "Move \n")
    } else if (event$type == 'key_press') {
      cat(co, "Key: ", event$char, " - integer value [", event$int, "]\n")
    }
  }
}


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Start the event loop. Press ESC to quit.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eventloop::run_loop(verbose, fps_target = 10, show_fps = TRUE)
```
