---
title: "ShadeBobs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ShadeBobs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval = FALSE}
library(eventloop)
library(grid)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Draw a rotating/expanding starfield
#
#  Standard variables defined as part of rendering framework
#  - x, y         coordinates of mouse in npc i.e. range [0, 1]
#  - width,height dimensions of window in pixels
#  - fps          frames per second in last 100 frames
#  - frame        current frame number (integer sequence starting from 1)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
colours <- ggplot2::alpha(rainbow(100), 0.1)
col_idx <- 1L

shadebob <- function() {

  # Expand points around centre
  xt <- 0.5 + 0.45 * sin(frame/10     ) #+ 0.3 * cos(frame/ 80 + pi/2)
  yt <- 0.5 + 0.3  * cos(frame/ 7 + pi) + 0.1 * sin(frame/ 4)

  # cycle the colour every 100 frames
  if (frame %% 100 == 0) {
    col_idx <<- col_idx + 1L
  }

  col <- colours[col_idx %% 100 + 1L]

  # Add points
  grid::grid.circle(
    x = grid::unit(xt, 'npc'),
    y = grid::unit(yt, 'npc'),
    r = grid::unit(20, 'pt'),
    gp = grid::gpar(fill = col, col = NA)
  )

  grid::grid.rect(x = 0, y = 0, width = 0.5, height = 0.1,
                  gp = grid::gpar(fill = 'white'))
  grid::grid.text(
    label = paste("FPS:", round(fps)), x = 0.01, y = 0.01,
    just = c('left', 'bottom'), gp = grid::gpar(fontfamily = 'mono', cex = 2)
  )
}


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Start an interactive render loop around this function
# Note: Your OS must support this device:  x11(type = 'dbcairo')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_loop(shadebob)

```
